name: Update Package Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup GIT
        run: |
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git config --global user.name "{{ github.actor }}"
      - name: Automated Version Bump
        run: npm version minor -m "Update Version to %s"
      - name: Commit Version Bump
        run: |
          git show --summary
          git add -A
          git commit -m 'Update Version'
          git push -u origin main
