name: Update Package Version

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
        env:
          token: ${{ github.token }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Version Bump
        run: |
          git switch -c update-package-version
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git config --global user.name "{{ github.actor }}"
          npm version minor -m "Update Version to %s"
          git show --summary
          git add package.json
          git push -u origin update-package-version
